Assignment 3

In [3]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.graph_objects as go
from  plotly.subplots import make_subplots

np.random.seed(613)

In [4]:
#import Wages by education level data sheet from Ontario government website
df = pd.read_csv("https://data.ontario.ca/dataset/1f14addd-e4fc-4a07-9982-ad98db07ef86/resource/4cc07c1b-62ed-4ece-a2a4-d05d0f45081c/download/img-wage-rate-by-edu-age-sex-ft-pt-ca-on-2006-24.csv",  
                 on_bad_lines = 'skip')
df

,YEAR,GEOGRAPHY,IMMIGRANT,TYPE OF WORK,WAGE RATE,EDUCATION,AGE GROUP,Both sexes,Men,Women
0,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",15 +,17.5,19.2,16.0
1,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 +,19.4,21.5,17.5
2,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 - 34,18.0,19.0,16.8
3,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 - 54,19.5,21.5,17.8
4,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 - 64,19.5,21.5,17.6
...,...,...,...,...,...,...,...,...,...,...
41035,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,15 +,35.0,33.6,35.6
41036,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 +,38.5,36.6,38.5
41037,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 - 34,35.0,30.0,35.5
41038,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 - 54,37.5,33.0,39.5
41039,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 - 64,38.5,36.6,39.0

In [5]:
df["TYPE OF WORK"].unique() #check the unique values in Type of work column

array(['All employees', ' Full-time', ' Part-time'], dtype=object)

In [6]:
df["YEAR"].unique() #check the unique values in Year column

array([2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024])

In [7]:
df.info() #check the data types for each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41040 entries, 0 to 41039
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   YEAR          41040 non-null  int64
 1   GEOGRAPHY     41040 non-null  object
 2   IMMIGRANT     41040 non-null  object
 3   TYPE OF WORK  41040 non-null  object
 4   WAGE RATE     41040 non-null  object
 5   EDUCATION     41040 non-null  object
 6   AGE GROUP     41040 non-null  object
 7   Both sexes    41040 non-null  float64
 8    Men          41040 non-null  float64
 9    Women        41040 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 3.1+ MB

In [21]:
df = df.rename(columns={"YEAR": "Year", " Men": "Men", " Women": "Women"}) #rename column to remove leanding space and all caps
df

,Year,GEOGRAPHY,IMMIGRANT,TYPE OF WORK,WAGE RATE,EDUCATION,AGE GROUP,Both sexes,Men,Women
0,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",15 +,17.5,19.2,16.0
1,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 +,19.4,21.5,17.5
2,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 - 34,18.0,19.0,16.8
3,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 - 54,19.5,21.5,17.8
4,2006,Canada,Total,All employees,Median hourly wage,"Total, all education levels",25 - 64,19.5,21.5,17.6
...,...,...,...,...,...,...,...,...,...,...
41035,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,15 +,35.0,33.6,35.6
41036,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 +,38.5,36.6,38.5
41037,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 - 34,35.0,30.0,35.5
41038,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 - 54,37.5,33.0,39.5
41039,2024,Ontario,Born in Canada,Part-time,Median hourly wage,Above bachelor's degree,25 - 64,38.5,36.6,39.0

In [40]:
new_df = df[(df["TYPE OF WORK"] == " Full-time")].copy() #copy into new dataframe with only full time work data
new_df
group_new_df = new_df.groupby("Year")[["Men", "Women"]].mean().round(2).reset_index() #group by year and then calculate the mean wages for Men and Women. Round to 2 decimal places. Set new index
final = group_new_df.assign(Wage_Gap = group_new_df["Men"] - group_new_df["Women"]) #calculate the wage gap by subtracting wage between men and women

In [41]:
final

    Year    Men  Women  Wage_Gap
0   2006  20.08  15.93      4.15
1   2007  20.39  16.40      3.99
2   2008  20.98  16.99      3.99
3   2009  21.08  17.25      3.83
4   2010  21.38  17.29      4.09
5   2011  21.92  17.81      4.11
6   2012  21.99  17.88      4.11
7   2013  22.28  18.22      4.06
8   2014  22.75  18.31      4.44
9   2015  23.14  18.86      4.28
10  2016  23.56  19.16      4.40
11  2017  24.34  19.46      4.88
12  2018  24.66  19.81      4.85
13  2019  25.39  20.75      4.64
14  2020  26.01  21.45      4.56
15  2021  26.86  22.17      4.69
16  2022  29.19  23.17      6.02
17  2023  30.04  24.66      5.38
18  2024  30.98  25.68      5.30

In [43]:

graph = make_subplots(rows=1, cols=1, specs=[[{"secondary_y": True}]]) #create a subplot with secondary y-axis

#add bar graph for women
graph.add_trace(
    go.Bar(name="Women", 
           x=final["Year"], 
           y=final["Women"], 
           marker_color="#ff719d"), 
           secondary_y=False)

#add bar graph for men
graph.add_trace(
    go.Bar(name="Men", 
           x=final["Year"], 
           y=final["Men"], 
           marker_color="#d3e2ff"), 
           secondary_y=False)

#add line graph for wage gap
graph.add_trace(
    go.Scatter(
        x=final["Year"], 
        y=final["Wage_Gap"], 
        mode="lines+markers", 
        name="Wage Gap", 
        line=dict(color="indigo", 
                  width=3)), 
        secondary_y=True)


graph.update_layout(barmode='relative',   #set bar mode to relative to show the wage gap between men and women
                    title="Wage Discrepancy Between Men and Women betweem 2006 - 2024 (Full-Time Workers)", #add title to the graph
                    xaxis_title="Year", #set x-axis title
                    xaxis_range=[2005.5, 2024.5], #set x-axis range to show all years clearly
                    yaxis_title="Average Wage Rate ($/hr)", #set y-axis title for the bar graph
                    yaxis2_title="Wage Gap ($/hr)", #set secondary y-axis title for the line graph
                    legend_title="Legend",
                    template="plotly_white")

graph.show()